# Generated by Django 5.2.3 on 2025-06-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='UserJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ujs_full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('ujs_username', models.CharField(max_length=150, unique=True)),
                ('ujs_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ujs_date_of_birth', models.DateField(blank=True, null=True)),
                ('ujs_email', models.EmailField(max_length=254, unique=True)),
                ('ujs_password', models.CharField(max_length=128)),
                ('ujs_address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'UserJobSeekers',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(blank=True, max_length=50, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skill')),
                ('ujs_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.userjobseeker')),
            ],
            options={
                'verbose_name_plural': 'User Skills',
                'unique_together': {('ujs_full_name', 'skill')},
            },
        ),
    ]
