# Generated by Django 5.2.3 on 2025-06-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobseeker',
            name='areas_of_Interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
