# Generated by Django 5.2.3 on 2025-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_userjobseeker_profile_image_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
        migrations.AddField(
            model_name='userjobseeker',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
