# Generated by Django 5.2.3 on 2025-06-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_company_company_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_events', to='main.expert'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_events', to='main.mentor'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='main.userjobseeker')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
    ]
