# Generated by Django 5.2.3 on 2025-06-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_newsevent_expert_newsevent_mentor_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('docx', 'Word Document'), ('url', 'External URL')], max_length=10)),
                ('created_by_id', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, help_text='Upload a file if content_type is pdf, video, or docx', null=True, upload_to='content_files/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image (e.g. video preview or PDF cover)', null=True, upload_to='content_thumbnails/')),
                ('url', models.URLField(blank=True, help_text='Only required if content_type is url', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_ct', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'main'), ('model__in', ['expert', 'mentor', 'company'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('skills', models.ManyToManyField(blank=True, related_name='contents', to='main.skill')),
            ],
            options={
                'verbose_name_plural': 'Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
