# Generated by Django 5.2.3 on 2025-06-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('docx', 'Word Document'), ('pptx', 'Presentation File'), ('url', 'External URL')], max_length=10),
        ),
    ]
